language: c
before_script: ./bootstrap
install:
  - wget https://github.com/dukesoferl/fw/archive/rpm-0_9_1-noarch.tar.gz -O fw-0.9.1.tar.gz
  - tar -xzvf fw-0.9.1.tar.gz
  - cd fw-rpm-0_9_1-noarch && ./bootstrap && ./configure --prefix=$HOME && make && make install && cd ..
  - export PATH=$PATH:$HOME/bin
