#! /bin/sh

set -e

#---------------------------------------------------------------------
#                            post-remove
# 
# Executed after the package is removed.
#
# http://code.google.com/p/fwtemplates/wiki/PackageHooks
#---------------------------------------------------------------------

case "$1" in
  upgrade)
    # defer to newer package's script
    exit 1
    ;;
  failed-upgrade)
    # actually handle the upgrade here
    # old-version is $2
    ;;
  remove)
    # undo permission changes from install
    if test -d /etc/erlrc.d/nodes ; then
      chown root:root /etc/erlrc.d/nodes
    fi

    # remove user (also appears to remove group)
    userdel erlang

    # remove runtime directories
    rm -rf /var/run/erlang
    ;;
  *)
    ;;
esac

exit 0
